=== sunwindroom/L2J_Mobius/L2J_Mobius_Essence_7.3_SevenSigns/dist/game/data/scripts/events/BalthusFestival/rewards.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="parameters">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" use="optional" />
											<xs:attribute type="xs:string" name="value" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="reward" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="items">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="item" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:int" name="id" use="optional" />
														<xs:attribute type="xs:long" name="count" use="optional" />
														<xs:attribute type="xs:double" name="chance" use="optional" />
														<xs:attribute type="xs:double" name="lotteryChance" use="optional" />
														<xs:attribute type="xs:int" name="enchant" use="optional" />
														<xs:attribute type="xs:boolean" name="redeemInAnyCase" use="optional" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:byte" name="from" use="optional" />
						<xs:attribute type="xs:byte" name="to" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== sunwindroom/L2J_Mobius/L2J_Mobius_Essence_7.3_SevenSigns/dist/game/data/scripts/events/BalthusFestival/rewards.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rewards.xsd">
	<parameters>
		<param name="give_coin_only_if_redeem" value="true" />
		<param name="minLevel" value="65" />
		<param name="try_to_roll_per_hour" value="5" /> <!-- min 1, max 40, default 5 (client supports max 5, but can increase / reduce) -->
		<param name="announce_by_ex_item_announce" value="true" /> <!-- [player_name] has obtained [item_name] from the Secret Shop! -->
		<param name="announce_by_system_message" value="true" /> <!-- If true - winner will be announce by system message -->
		<param name="show_name_in_announce" value="true" /> <!-- If true - winner name will be showed. If false - not showed. Works with announce_by_system_message -->

		<param name="coin_id" value="49783" /> <!-- Balthus Knights' Mark (Time-limited) [Sealed] -->
		<param name="coin_count" value="100" />
		<param name="daily_supply_enabled" value="true" />
		<param name="daily_supply_id" value="49782" /> <!-- Balthus Knights' Supply Box (Time-limited) [Sealed] -->
		<param name="daily_supply_count" value="1" />
		<param name="daily_supply_fee_enabled" value="true" />
		<param name="daily_supply_fee_id" value="57" /> <!-- Adena -->
		<param name="daily_supply_fee_count" value="1" />

		<!-- If per period reward will redeem - it can take min-max players -->
		<param name="min_winner" value="1" />
		<param name="max_winner" value="1" />
		<param name="give_participation_reward_to_winner" value="true" />

		<param name="mailSubject_en" value="Balthus Knight Lottery" />
		<param name="mailContent_en" value="You win reward in Balthus Event!" />

		<param name="mailSubject_ru" value="Лотерея Рыцарей Балтуса" />
		<param name="mailContent_ru" value="Вы получили награду за участие в Лотерее Рыцарей Балтуса" />
	</parameters>

	<reward from="01" to="16">
		<items>
			<item id="49800" count="1" chance="1" lotteryChance="100" redeemInAnyCase="true" /> <!-- Sibi's Coin Pack -->
		</items>
	</reward>
	<reward from="17" to="17">
		<items>
			<item id="98345" count="1" chance="1" lotteryChance="100" redeemInAnyCase="true" /> <!-- Package: Talisman of Aden (20 pcs.) -->
		</items>
	</reward>
	<reward from="18" to="18">
		<items>
			<item id="98343" count="1" chance="1" lotteryChance="100" redeemInAnyCase="true" /> <!-- Package: Cloak of Protection (50 pcs.) -->
		</items>
	</reward>
	<reward from="19" to="19">
		<items>
			<item id="98339" count="1" chance="1" lotteryChance="100" redeemInAnyCase="true" /> <!-- Package: Dragon Belt (50 pcs.) -->
		</items>
	</reward>
	<reward from="20" to="20">
		<items>
			<item id="98295" count="1" chance="1" lotteryChance="100" redeemInAnyCase="true" /> <!-- Supply Coupon -->
		</items>
	</reward>
	<reward from="21" to="21">
		<items>
			<item id="49789" count="1" chance="1" lotteryChance="100" redeemInAnyCase="true" /> <!-- +8 B-grade Weapon Pack -->
		</items>
	</reward>
	<reward from="22" to="22">
		<items>
			<item id="49785" count="1" chance="1" lotteryChance="100" redeemInAnyCase="true" /> <!-- A-grade Weapon Pack -->
		</items>
	</reward>
	<reward from="23" to="23">
		<items>
			<item id="93263" count="1" chance="1" lotteryChance="100" redeemInAnyCase="true" /> <!-- +5 Top-grade A-grade Weapon Pack -->
		</items>
	</reward>
	<reward from="00" to="00">
		<items>
			<item id="96616" count="1" chance="1" lotteryChance="100" redeemInAnyCase="true" /> <!-- Boss' Weapon Pack -->
		</items>
	</reward>
</list>
